name: Run Python Script 24/7

on:
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой через вкладку Actions
  schedule:
    - cron: '0 */6 * * *' # Автоматический перезапуск робота каждые 6 часов

jobs:
  run-script:
    runs-on: ubuntu-latest # Запуск на чистой ОС Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Скачиваем файлы из твоего репозитория

      - name: Set up Python
        uses: actions/setup-python@v4 # Устанавливаем Python
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests # Устанавливаем библиотеку для запросов

      - name: Run Script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }} # Передаем скрытый токен из настроек репозитория
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Передаем URL вебхука Discord
          PYTHONUNBUFFERED: 1 # Отключаем задержку логов (вывод будет идти в реальном времени)
        run: python main.py # Запуск твоего Python-файла (убедись, что он называется именно main.py)
